config/routes.rb
Rails.application.routes.draw do

  devise_for :appusers
	root 'pages#home'
	get 'pages/home', to: 'pages#home'

	resources :appusers
	resources :projects do 
    resources :bugs, only: [:new, :create]
  end
  resources :bugs, except: [:new, :create]
	# get '/login', to: 'sessions#new'
 #    post '/login', to: 'sessions#create'
 #    delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

	has_many :user_projects, dependent: :destroy
  has_many :appusers, through: :user_projects
  has_many :bugs, dependent: :destroy
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource


	def index
    @projects = current_appuser.projects
	end

	def show
    @project = Project.find(params[:id])
    authorize! :read, @project
	end

	def new
    @project = Project.new
	end

	def create
    project = Project.new(project_params)

    users = params["appusers"].map(&:to_i)
    tempusers = Appuser.where(id: users)

    if @project.save 
      @project.appusers << tempusers
      flash[:success] = "#{@project.name.titleize} project created"
      redirect_to projects_path
    else
      flash[:danger] = "you select more users or select less"
      render 'new'
    end
    
	end

	def edit
    @project = Project.find(params[:id])
	end

	def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      flash[:success] = " #{@project.name} project updated successfully!"
      redirect_to project_path(@project)
    else
      render 'edit'
    end
	end

	def destroy
    @project = Project.find(params[:id])
    @project.destroy
    flash[:success] = "User #{@project.name} Project deleted successfully"

    redirect_to projects_path
	end

  private

    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description)
    end

end

app/views/projects/_form.html.erb
<br><br>
<div class="row">

  <div class="col-md-12" style="padding-left: 300px">
  <%= form_for(@project, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <div class="form-group" >
      <div class="control-label col-md-2">
        <%=f.label :name %>
      </div>
      <div class="col-md-8">
        <%= f.text_field :name, class: "form-control", placeholder: "Enter Your Name", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :description %>
      </div>
      <div class="col-md-8">
        <%= f.text_field :description,rows: 10, class: "form-control",placeholder: "Enter Email" %>
      </div>
    </div>
    <% if @project.new_record? %>
      <%= f.select_tag "appusers[]", options_for_select(Appuser.all.map {|k, v| [k.name+"  "+k.user_type, k.id]}),{:multiple => :multiple, :size => 10}  %>
    <% end %>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.submit(@project.new_record? ? "Create my account" : "Update", class: "btn btn-primary btn-lg btn-xlarge") %>
      </div>
    </div>
  <% end %>
  <div class="colormatch" style="padding-left: 15px">
    [ <%= link_to "Cancel request and return to recipes listing", projects_path %> ]
  </div>
  <br><br><br><br>
  </div>
</div>

app/views/projects/_list.html.erb
<br>
<h1 align="center">List of project's</h1>
<hr />


<div align="center">
  <% @projects.each do |project| %>
    <ul class="listing">
      <div class="row" style="padding-left: 450px;">
        <div class="well col-md-4 col-md-offset-4" style=" background-color: #eee;">  
          <br>  
          <li class="user-title"><%= link_to project.name, project_path(project) %></li>
          <br>    
          <% if params[:user_id] == nil %>
            <% if can? :create, Bug %>
              <li><%= link_to "add bug", "/projects/#{project.id}/bugs/new" %></li>
            <% end %>     
            <% if can? :delete, project %>
              <li><%= link_to "Delete this user", project_path(project), method: :delete %></li>
            <% end %>
          <% elsif current_appuser.id != params[:user_id] %>
              <li><%= link_to "Add this project", "/appusers/#{params[:user_id]}/projects/#{project.id}" %></li>
          <% end %>
        </div>
      </div>
    </ul>
  <% end %>
</div>

app/views/projects/edit.html.erb
<%= render 'form' %>

app/views/projects/index.html.erb
<%= render 'list' %>

app/views/projects/new.html.erb
<%= render 'form' %>

app/views/projects/show.html.erb
<br>
<h1 align="center">Project Name:<%= @project.name %></h1>
<hr />
<br><br>
<div class="row">
  <div class="col-md-8 well" style="padding-left: 100px;">
    <h2>Name: <%= @project.name %> </h2>
    <p>Description: <%= @project.description %></p>
    <p>Manager: <% manager = @project.appusers.find_by(user_type: "manager") %>
      <% if manager != nil %>
        <%= link_to manager.name, appuser_path(manager) %></p>
      <% end %>
    <p>Developer: <% developer = @project.appusers.find_by(user_type: "developer") %>
      <% if developer != nil %>
        <%= link_to developer.name, appuser_path(developer) %></p>
      <% end %>
      <p>Quality Assurance: <% qa = @project.appusers.find_by(user_type: "qa") %>
      <% if qa != nil %>
        <%= link_to qa.name, appuser_path(qa) %></p>
      <% end %>
    <% if can? :create, Bug %>
      <%= link_to "add bug", "/projects/#{@project.id}/bugs/new" %>
    <% end %>   
    <br>
  </div>
  <div class="col-md-8 well" style=" padding-left: 100px;">
    <div class="recipe-actions ">
      <% if can? :edit, @project %>
        <%= link_to "Edit Profile", edit_project_path(@project), class: "btn btn-xs btn-warning " %>
      <% end %>
      <% if can? :delete, @project %>
        <%= link_to "Delete Profile", project_path(@project) , method: :delete, class: "btn btn-xs btn-danger", data: { confirm: "Are you sure you want to delete this recipe?"} %>
      <% end %>
      <%= link_to "Return to Projects list", projects_path , class: "btn btn-xs btn-primary" %>
    </div>
  </div>
</div>
<br>
<hr />