config/routes.rb
Rails.application.routes.draw do

  devise_for :appusers
	root 'pages#home'
	get 'pages/home', to: 'pages#home'

	resources :appusers
	resources :projects do 
    resources :bugs, only: [:new, :create]
  end
  resources :bugs, except: [:new, :create]
	# get '/login', to: 'sessions#new'
 #    post '/login', to: 'sessions#create'
 #    delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/appuser.rb
class Appuser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable


  validates :name, presence: true, length: {maximum: 30}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
                    format: {with: VALID_EMAIL_REGEX }
  validates_uniqueness_of :email
  validates :password, presence: true, length: {minimum: 5}, allow_nil: true
  enum user_type: [:manager, :developer, :qa]
  validates :user_type, presence: true
  has_many :user_projects, dependent: :destroy
  has_many :projects, through: :user_projects
  has_many :user_bugs, dependent: :destroy
  has_many :bugs, through: :user_bugs

end

app/controllers/appusers_controller.rb
class AppusersController < ApplicationController
	load_and_authorize_resource
	
	def index
		@users = Appuser.all
	end

	def edit
		@user = Appuser.find(params[:id])
	end

	def selectproject		
		@user = Appuser.find(params[:user_id])
		if @user.user_type != 'manager'
			@projects = Project.all
		else
			flash[:danger] = "Cannot add manager to this project"
			redirect_to appusers_path
		end
	end

	def addproject
		@project = Project.find(params[:project_id])
		@user = Appuser.find(params[:user_id])
		if !@project.appusers.find_by(user_type: @user.user_type)
			if @user.projects << @project

				flash[:success] = "project successfully added"
				redirect_to appuser_path(@user)
			else
				flash[:danger] = "something wrong with your selection"
				redirect_to appusers_path
			end
		else
			flash[:danger] = "#{@user.user_type} Already added to this project"
			redirect_to appusers_path
		end
	end

	def update
		@user = Appuser.find(params[:id])
		user_t=params[:user_type].to_i
		user=user_params
		user[:user_type]=user_t

		if @user.update(user)
			flash[:success] = " #{@user.name}'s profile updated successfully!"
			redirect_to appuser_path(@user)
		else
			render 'edit'
		end
	end

	def destroy
		@user = Appuser.find(params[:id])
		@user.destroy
		flash[:success] = "User #{@user.name}'s profile deleted successfully"

		redirect_to appusers_path
	end

	def show 
		@user = Appuser.find(params[:id])
	end

	private

		def user_params
			params.require(:appuser).permit(:name, :email, :password, :password_confirmation, :user_type)
		end
end

app/views/appusers/_form.html.erb
<br><br>
<div class="row">

	<div class="col-md-12" style="padding-left: 300px">
	<%= form_for(@user, :html => {class: "form-horizontal", role: "form"}) do |f| %>

		<div class="form-group" >
			<div class="control-label col-md-2">
				<%=f.label :name %>
			</div>
			<div class="col-md-8">
				<%= f.text_field :name, class: "form-control", placeholder: "Enter Your Name", autofocus: true %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-md-2">
				<%= f.label :email %>
			</div>
			<div class="col-md-8">
				<%= f.email_field :email, class: "form-control",placeholder: "Enter Email" %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-md-2">
				<%= f.label :password %>
			</div>
			<div class="col-md-8">
				<%= f.password_field :password, rows: 1, class: "form-control",placeholder: "Choose a password" %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-md-8">
				<%= f.label :password_confirmation, "Confirm Password" %>
			</div>
			<div class="col-md-8">
				<%= f.password_field :password_confirmation, rows: 1, class: "form-control",placeholder: "Confirm the password" %>
			</div>
		</div>
		<div class="form-group">
			<div class="control-label col-md-8">
				<%= f.label :user_type, "select user type" %>
			</div>
			<div class="col-md-8" >
				<%= f.select_tag :user_type, options_for_select(Appuser.user_types.map {|k, v| [k, v]}) %>
			</div>
    	</div>
		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<%= f.submit(@user.new_record? ? "Create my account" : "Update", class: "btn btn-primary btn-lg btn-xlarge") %>
			</div>
		</div>
	<% end %>
	<div class="colormatch" style="padding-left: 15px">
		[ <%= link_to "Cancel request and return to recipes listing", appusers_path %> ]
	</div>
	<br><br><br><br>
	</div>
</div>

app/views/appusers/edit.html.erb
<%= render 'form' %>

app/views/appusers/index.html.erb
<br>
<h1 align="center">List of user's</h1>
<hr />


<div align="center">
	<% @users.each do |user| %>
		<ul class="listing">
			<div class="row" style="padding-left: 450px;">
				<div class="well col-md-4 col-md-offset-4" style=" background-color: #eee;">	
					<br>	
					<li><%= link_to gravatar_for(user), appuser_path(user) %></li>
					<li class="user-title"><%= link_to user.name, appuser_path(user) %></li>
					<% if can? :edit, Project %>
						<% if user.user_type != "manager" %>
							<li><%= link_to "Add this user to project", "/appusers/#{user.id}/projects" %></li>
						<% end %>
					<% end %>
					<% if can? :delete, user %>
						<% if current_appuser != user %>
							<li><%= link_to "Delete this user", appuser_path(user), method: :delete %></li>
						<% end %>
					<% end %>
				</div>
			</div>
		</ul>
	<% end %>
</div>

app/views/appusers/new.html.erb
<%= render 'form' %>

app/views/appusers/selectproject.html.erb
<% if current_appuser.user_type="manager" %>
  <%= render '/projects/list' %>
<% else %>
  <h1>Only manager can access this file</h1>
<% end %>

app/views/appusers/show.html.erb
<br>
<h1 align="center"><%= @user.name.capitalize %>'s profile</h1>
<hr />
<br><br>
<div class="row">
	<div class="col-md-4 col-md-offset-4 center" style="padding-left: 600px;">
		<%= gravatar_for @user, size: 150, class:"circle" %>
	</div>
	<div class="col-md-8 well" style="padding-left: 100px;">
		<h2>Type: <%= @user.user_type %> </h2>
	</div>
	<div class="col-md-8 well" style=" padding-left: 100px;">
		<div class="recipe-actions ">
			<% if can? :edit, Appuser %>
				<% if current_appuser==@user %>
					<%= link_to "Edit Profile", edit_appuser_path(@user), class: "btn btn-xs btn-warning " %>
				<% end %>
			<% elsif can? :delete, Appuser %>		
				<%= link_to "Delete Profile", appuser_path(@user), method: :delete, class: "btn btn-xs btn-danger", data: { confirm: "Are you sure you want to delete this recipe?"} %>
			<% end %>
			<%= link_to "Return to Users list", appusers_path, class: "btn btn-xs btn-primary" %>
		</div>
	</div>
</div>
<br>
<hr />