config/routes.rb
Rails.application.routes.draw do

  devise_for :appusers
	root 'pages#home'
	get 'pages/home', to: 'pages#home'

	resources :appusers
	resources :projects do 
    resources :bugs, only: [:new, :create]
  end
  resources :bugs, except: [:new, :create]
	# get '/login', to: 'sessions#new'
 #    post '/login', to: 'sessions#create'
 #    delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bug.rb
class Bug < ApplicationRecord
	

  has_attached_file :screenshot, styles: { large: "600*600>", medium: "300*300>", thumb: "150*150#"}
  validates_attachment_content_type :screenshot, content_type: /\Aimage\/.*\Z/ 
	has_many :user_bugs
  has_many :appusers, through: :user_bugs
  enum bug_type: [:bug, :feature]
	enum status: [:zero, :started, :completed, :resolved]
	belongs_to :project
  validates_uniqueness_of :title

	
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  load_and_authorize_resource

  def index
    @bugs=current_appuser.bugs
  end

  def new 
    @bug = Bug.new
    @project = Project.find_by(id: params[:project_id])
  end

  def create
    bug=bug_params
    bug[:deadline]=params[:deadline].to_i
    @bug = Bug.new(bug)
    project = Project.find_by(id: params[:project_id])
    users = params["appusers"].map(&:to_i)
    tempusers = Appuser.where(id: users)
 
    if project.bugs << @bug
      @bug.appusers << tempusers

      flash[:success] = "#{@bug.title.titleize} bug created"
      redirect_to bug_path(@bug)
    else
      flash[:success] = "#{bug} bug not created"
      render 'new'
    end 
  end

  def edit
    @bug = Bug.find(params[:id])
  end

  def update
    @bug = Bug.find(params[:id])

    if @bug.update(bug_params)
      flash[:success] = " #{@bug.bug_type} project updated successfully!"
      redirect_to bug_path(@bug)
    else
      render 'edit'
    end
  end

  def destroy
    @bug = Bug.find(params[:id])
    @bug.destroy
    flash[:success] = "#{@bug.bug_type} deleted successfully"

    redirect_to bugs_path
  end

  def show 
    @bug = Bug.find(params[:id])
    authorize! :read, @bug
  end

  private

    def set_bug
      @bug = Bug.find(params[:id])
    end

    def bug_params
      params.require(:bug).permit(:title, :description, :deadline, :bug_type, :status, :screenshot)
    end

end

app/views/bugs/_form.html.erb
<br><br>
<div class="row">

  <div class="col-md-12" style="padding-left: 300px">
  <%= form_for(@bug, :html => {class: "form-horizontal", role: "form"}) do |f| %>

    <div class="form-group" >
      <div class="control-label col-md-2">
        <%=f.label :title %>
      </div>
      <div class="col-md-8">
        <%= f.text_field :title, class: "form-control", placeholder: "Enter Your Name", autofocus: true %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :description %>
      </div>
      <div class="col-md-8">
        <%= f.text_field :description,rows: 10, class: "form-control",placeholder: "Enter Email" %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :deadline,"Enter days " %>
      </div>
      <div class="col-md-8">
        <%= f.number_field :deadline, class: "form-control",placeholder: "0" %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-8">
        <%= f.label :bug_type, "select type" %>
      </div>
      <div class="col-md-8" >
        <%= f.select :bug_type, options_for_select([["Bug", "bug"], ["Feature", "feature"]]) %>
      </div>      
    </div>
    <div class="form-group">
      <div class="control-label col-md-8">
        <%= f.label :status, "select type" %>
      </div>
      <div class="col-md-8" >
        <%= f.select :status, options_for_select([["New", "zero"], ["Started", "started"], ["Completed", "completed"], ["Resolved", "resolved"]]) %>      
      </div>      
    </div>
    
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.submit(@bug.new_record? ? "Create bug" : "Update bug", class: "btn btn-primary btn-lg btn-xlarge") %>
      </div>
    </div>
  <% end %>
  <div class="colormatch" style="padding-left: 15px">
    [ <%= link_to "Cancel request and return to bugs listing", bugs_path %> ]
  </div>
  <br><br><br><br>
  </div>
</div>

app/views/bugs/_list.html.erb
<br>
<h1 align="center">List of project's</h1>
<hr />


<div align="center">
  <% @bugs.each do |bug| %>
    <ul class="listing">
      <div class="row" style="padding-left: 450px;">
        <div class="well col-md-4 col-md-offset-4" style=" background-color: #eee;">  
          <br>  
          <li class="user-title"><%= link_to bug.title, bug_path(bug) %></li>
            <li>  <p><Strong>Description: </Strong> <%= bug.description %></p></li>
            <br>
            <li> <p><Strong>Type: </Strong> <%= bug.bug_type %></p></li>
            <li> <p><Strong>Status: </Strong> <%= bug.status %></p></li>
          <li><%= link_to "Delete this user", bug_path(bug), method: :delete %></li>
          
        </div>
      </div>
    </ul>
  <% end %>
</div>

app/views/bugs/edit.html.erb
<%= render 'form' %>

app/views/bugs/index.html.erb
<%= render 'list' %>

app/views/bugs/new.html.erb
<br><br>
<div class="row">

  <div class="col-md-12" style="padding-left: 300px">
  <%= form_for([@project, @bug], :html => {class: "form-horizontal", role: "form", multipart: true}) do |f| %>

    <div class="form-group" >
      <div class="control-label col-md-2">
        <%=f.label :title %>
      </div>
      <div class="col-md-8">
        <%= f.text_field :title, class: "form-control", placeholder: "Enter Your Name", autofocus: true %>
      </div>
    </div>
    <div class="form-group" >
      <div class="control-label col-md-2">
        <%=f.label :screenshot %>
      </div>
      <div class="col-md-8">
        <%= f.file_field :screenshot, class: "form-control" %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :description %>
      </div>
      <div class="col-md-8">
        <%= f.text_field :description,rows: 10, class: "form-control",placeholder: "Enter Email" %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :deadline,"Enter days " %>
      </div>
      <div class="col-md-8">
        <%= f.number_field :deadline, class: "form-control",placeholder: "0" %>
      </div>
    </div>
    <div class="form-group">
      <div class="control-label col-md-8">
        <%= f.label :bug_type, "select type" %>
      </div>
      <div class="col-md-8" >
        <%= f.select :bug_type, options_for_select([["Bug", "bug"], ["Feature", "feature"]]) %>
      </div>      
    </div>
    <div class="form-group">
      <div class="control-label col-md-8">
        <%= f.label :status, "select type" %>
      </div>
      <div class="col-md-8" >
        <%= f.select :status, options_for_select([["New", "zero"], ["Started", "started"], ["Completed", "completed"], ["Resolved", "resolved"]]) %>      
      </div>      
    </div>
    <% if @bug.new_record? %>
      <%= f.select_tag "appusers[]", options_for_select(Appuser.all.map {|k, v| [k.name+"  "+k.user_type, k.id]}),{:multiple => :multiple, :size => 10}  %>
    <% end %>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.submit(@bug.new_record? ? "Create bug" : "Update bug", class: "btn btn-primary btn-lg btn-xlarge") %>
      </div>
    </div>
  <% end %>
  <div class="colormatch" style="padding-left: 15px">
    [ <%= link_to "Cancel request and return to bugs listing", bugs_path %> ]
  </div>
  <br><br><br><br>
  </div>
</div>

app/views/bugs/show.html.erb
<br>
<h1 align="center">Bug Name:<%= @bug.title.capitalize %></h1>
<hr />
<br><br>
<div class="row">
  <%= image_tag @bug.screenshot.url(:medium), style: "padding-left:50px;" %>
  <div class="col-md-8 well" style="padding-left: 100px;">
    <h2>Name: <%= @bug.title %> </h2>
    <p><Strong>Description: </Strong> <%= @bug.description %></p>
  

    <br>
    <p><Strong>Type: </Strong> <%= @bug.bug_type %></p>
    <p><Strong>Status: </Strong> <%= @bug.status %></p>
  </div>
  <div>
    <br>
  </div>

  <div class="col-md-8 well" style=" padding-left: 50px;">
    <div class="recipe-actions ">
      <% if can? :manage, Bug %>
        <%= link_to "Edit Profile", edit_bug_path(@bug), class: "btn btn-xs btn-warning " %>
        <%= link_to "Delete Profile", bug_path(@bug), method: :delete, class: "btn btn-xs btn-danger", data: { confirm: "Are you sure you want to delete this recipe?"} %>
      <% end %>
      <%= link_to "Return to Users list", bugs_path, class: "btn btn-xs btn-primary" %>
    </div>
  </div>
</div>
<br>
<hr />